apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diode.fullname" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/\w+\s+" | grep -v "grep >/dev/null"
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10 
          livenessProbe: 
            exec:
              command:
              - bash
              - '-c'
              - |
                ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/\w+\s+" | grep -v "grep >/dev/null"
            periodSeconds: 10
            failureThreshold: 10
          
          args:
            - |
              echo -e "Diode is starting...\n"
              {{ include "diode-command" . | nindent 14 }}
              {{- if .Values.logging.displayAddress.enabled }}
                echo -e "ADDRESSES: \n"
                {{- if .Values.localServer.base64PrivateKey.one }}
                  echo -e "=============================================================================\n"
                  echo "KEY 1 ADDRESS : https://$(diode --dbpath /go/diode/LOCALSERVER_BASE64PRIVATEKEY_ONE config 2>&1 | awk '/Client address/ { print $5 }').diode.link"
                {{- end }}
                {{- if .Values.localServer.base64PrivateKey.two }}
                  echo -e "=============================================================================\n"
                  echo "KEY 2 ADDRESS : https://$(diode --dbpath /go/diode/LOCALSERVER_BASE64PRIVATEKEY_TWO config 2>&1 | awk '/Client address/ { print $5 }').diode.link"
                {{- end }}
                {{- if .Values.localServer.base64PrivateKey.three }}
                  echo -e "=============================================================================\n"
                  echo "KEY 3 ADDRESS : https://$(diode --dbpath /go/diode/LOCALSERVER_BASE64PRIVATEKEY_THREE config 2>&1 | awk '/Client address/ { print $5 }').diode.link"
                {{- end }}
                {{- if .Values.localServer.base64PrivateKey.four }}
                  echo -e "=============================================================================\n"
                  echo "KEY 4 ADDRESS : https://$(diode --dbpath /go/diode/LOCALSERVER_BASE64PRIVATEKEY_FOUR config 2>&1 | awk '/Client address/ { print $5 }').diode.link"
                {{- end }}
                {{- if .Values.localServer.base64PrivateKey.five }}
                  echo -e "=============================================================================\n"
                  echo "KEY 5 ADDRESS : https://$(diode --dbpath /go/diode/LOCALSERVER_BASE64PRIVATEKEY_FIVE config 2>&1 | awk '/Client address/ { print $5 }').diode.link"
                {{- end }}
                echo -e "\n"
                echo -e "End Addreses\n"
              {{- end }}

              {{- if .Values.logging.displayProcess.enabled }}
                echo -e "Confirm diode is running...\n"
                # Get the list of processes matching the regex
                processes=$(ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/LOCALSERVER_BASE64PRIVATEKEY" | grep -v "grep >/dev/null" | awk '/root/ { for(i=8; i<=NF; i++) { printf("%s ", $i) } print "" }')

                # Count the number of matching processes
                count=$(echo "$processes" | wc -l)

                # Print the count
                echo "Number of running diode processes: $count"

                # Iterate over each matching process and print its details
                echo "$processes" | while read -r process; do
                  echo "Process details: $process"
                done
              {{- end }}
              tail -f /dev/null 
          volumeMounts:
            - name: {{ include "diode.fullname" . }}
              mountPath: /go/diode/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "diode.fullname" . }}
          secret:
            secretName: {{ include "diode.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}