apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diode.fullname" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/\w+\s+" | grep -v "grep >/dev/null"
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10 
          livenessProbe: 
            exec:
              command:
              - bash
              - '-c'
              - |
                ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/\w+\s+" | grep -v "grep >/dev/null"
            periodSeconds: 10
            failureThreshold: 10
          
          args:
            - |
              echo "Diode is starting"
              {{ include "diode-command" . | nindent 14 }}
              tail -f /dev/null 
          volumeMounts:
            - name: {{ include "diode.fullname" . }}
              mountPath: /go/diode/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "diode.fullname" . }}
          secret:
            secretName: {{ include "diode.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}