apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "diode.fullname" . }}"
data:
  {{- if .Values.base64PrivateKey.one }}
  BASE64PRIVATEKEY_ONE: {{ required "base64PrivateKey.one is required" .Values.base64PrivateKey.one | quote }}
  {{- end }}
  {{- if .Values.base64PrivateKey.two }}
  BASE64PRIVATEKEY_TWO: {{ required "base64PrivateKey.two" .Values.base64PrivateKey.two | quote }}
  {{- end }}
  {{- if .Values.base64PrivateKey.three }}
  BASE64PRIVATEKEY_THREE: {{ required "base64PrivateKey.three" .Values.base64PrivateKey.three | quote }}
  {{- end }}
  {{- if .Values.base64PrivateKey.four }}
  BASE64PRIVATEKEY_FOUR: {{ required "base64PrivateKey.four is required" .Values.base64PrivateKey.four | quote }}
  {{- end }}
  {{- if .Values.base64PrivateKey.five }}
  BASE64PRIVATEKEY_FIVE: {{ required "base64PrivateKey.five is required" .Values.base64PrivateKey.five | quote }}
  {{- end }}
stringData: 
  probe-check: |-
            #!/bin/bash

            # Get the list of processes matching the regex
            processes=$(ps aux | egrep "\-dbpath\s+\/\w+\/\w+\/BASE64PRIVATEKEY" | grep -v "grep >/dev/null")

            # Count the number of matching processes
            count=$(echo "$processes" | wc -l)

            # Check if count is greater than zero and return true or false
            if [ "$count" -gt 1 ]; then
              echo "true"
            else
              echo "false"
            fi

type: Opaque
