apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "diode.fullname" . }}"
data:
  {{- if .Values.localServer.base64PrivateKey.one }}
  LOCALSERVER_BASE64PRIVATEKEY_ONE: {{ required "localServer.base64PrivateKey.one is required" .Values.localServer.base64PrivateKey.one | quote }}
  {{- end }}
  {{- if .Values.localServer.base64PrivateKey.two }}
  LOCALSERVER_BASE64PRIVATEKEY_TWO: {{ required "localServer.base64PrivateKey.two" .Values.localServer.base64PrivateKey.two | quote }}
  {{- end }}
  {{- if .Values.localServer.base64PrivateKey.three }}
  LOCALSERVER_BASE64PRIVATEKEY_THREE: {{ required "localServer.base64PrivateKey.three" .Values.localServer.base64PrivateKey.three | quote }}
  {{- end }}
  {{- if .Values.localServer.base64PrivateKey.four }}
  LOCALSERVER_BASE64PRIVATEKEY_FOUR: {{ required "localServer.base64PrivateKey.four is required" .Values.localServer.base64PrivateKey.four | quote }}
  {{- end }}
  {{- if .Values.localServer.base64PrivateKey.five }}
  LOCALSERVER_BASE64PRIVATEKEY_FIVE: {{ required "localServer.base64PrivateKey.five is required" .Values.localServer.base64PrivateKey.five | quote }}
  {{- end }}
type: Opaque
