apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "diode-chart.fullname" . }}"
stringData:
  LOCAL_DIODE_SVC_CLUSTERIP: {{ required "service.clusterIP is required" .Values.service.clusterIP | quote }}
  LOCAL_DIODE_SVC_PORT: {{ required "service.port" .Values.service.port | quote }}
  LOCAL_DIODE_TARGET_PORT: {{ required "service.targetPort" .Values.service.targetPort | quote }}
  LOCAL_DIODE_HEX: {{ required "diodeConfiguration.localServer.diodeHex is required" .Values.diodeConfiguration.localServer.diodeHex | quote }}
  LOCAL_DIODE_PINATA: {{ required "diodeConfiguration.localServer.diodePinata is required" .Values.diodeConfiguration.localServer.diodePinata | quote }}
  LOCAL_DIODE_KEY_NAME: {{ required "diodeConfiguration.localServer.diodeKeyName is required" .Values.diodeConfiguration.localServer.diodeKeyName | quote }}
  LOCAL_DIODE_PROTOCOL: {{ required "diodeConfiguration.localServer.protocol is required" .Values.diodeConfiguration.localServer.protocol | default "tls" | quote }}
  LOCAL_DIODE_MODE: {{ required "diodeConfiguration.localServer.mode is required" .Values.diodeConfiguration.localServer.mode | quote }}
  LOCAL_PUBLISH_TYPE: {{ required "diodeConfiguration.localServer.publishType is required" .Values.diodeConfiguration.localServer.publishType | default "public" | quote }}
  REMOTE_DIODE_HEX: {{ required "diodeConfiguration.remoteServer.remoteDiodeHex is required" .Values.diodeConfiguration.remoteServer.remoteDiodeHex | quote }}
  REMOTE_DIODE_PORT: {{ .Values.diodeConfiguration.remoteServer.port | quote  }}
  REMOTE_DIODE_HOST: {{ include "diode-chart.fullname" . }}.{{ .Release.Namespace | default "default" }}.svc.cluster.local
  REMOTE_DIODE_PROTOCOL: {{ required "diodeConfiguration.remoteServer.protocol is required" .Values.diodeConfiguration.remoteServer.protocol | quote }}
  REMOTE_PUBLISH_TYPE: {{ required "diodeConfiguration.remoteServer.publishType is required" .Values.diodeConfiguration.remoteServer.publishType | default "public" | quote }}
type: Opaque

# diode --dbpath=/go/diode/YUGA --debug true publish -private 10.43.195.27:5433:5433,0xe9a569faf05456b3c8acdc8b8de9552b139d617c -proxy_port 5433